# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('phone_no', models.CharField(max_length=250, null=True)),
                ('dob', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('special_skill', models.CharField(max_length=250, null=True)),
                ('fav_game', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
