# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=2, max_length=250, upload_to=''),
            preserve_default=False,
        ),
    ]
