# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
