# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180323_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('available_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('player_req', models.IntegerField(null=True)),
                ('ground_name', models.CharField(max_length=50, null=True)),
                ('player_list', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='player_id',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_game',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score_or_prev_game',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
