# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180415_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_first_name', models.CharField(max_length=50, null=True)),
                ('organizer_last_name', models.CharField(max_length=50, null=True)),
                ('tournament_name', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('player_req', models.IntegerField(null=True)),
                ('ground_name', models.CharField(max_length=50, null=True)),
                ('player_list', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
