# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180415_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AlterField(
            model_name='ground',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
