# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180416_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
