# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
