# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180421_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
