# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ground_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='end_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='rent_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='start_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
