# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180423_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='available_status',
            field=models.IntegerField(),
        ),
    ]
