# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180423_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='sport_type_for_rent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
